// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolos2.Data;

#nullable disable

namespace kolos2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kolos2.Models.Backpack", b =>
                {
                    b.Property<int>("IdCharacter")
                        .HasColumnType("int");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("IdCharacter", "IdItem");

                    b.HasIndex("IdItem");

                    b.ToTable("backpacks");

                    b.HasData(
                        new
                        {
                            IdCharacter = 1,
                            IdItem = 1,
                            Amount = 2
                        },
                        new
                        {
                            IdCharacter = 2,
                            IdItem = 2,
                            Amount = 1
                        },
                        new
                        {
                            IdCharacter = 3,
                            IdItem = 3,
                            Amount = 2
                        });
                });

            modelBuilder.Entity("kolos2.Models.Character", b =>
                {
                    b.Property<int>("IdCharacter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCharacter"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("IdCharacter");

                    b.ToTable("characters");

                    b.HasData(
                        new
                        {
                            IdCharacter = 1,
                            CurrentWeight = 12,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            MaxWeight = 30
                        },
                        new
                        {
                            IdCharacter = 2,
                            CurrentWeight = 10,
                            FirstName = "Janina",
                            LastName = "Kowalska",
                            MaxWeight = 20
                        },
                        new
                        {
                            IdCharacter = 3,
                            CurrentWeight = 15,
                            FirstName = "Janusz",
                            LastName = "Drabina",
                            MaxWeight = 25
                        },
                        new
                        {
                            IdCharacter = 4,
                            CurrentWeight = 1,
                            FirstName = "Joasia",
                            LastName = "Nowak",
                            MaxWeight = 10
                        },
                        new
                        {
                            IdCharacter = 5,
                            CurrentWeight = 0,
                            FirstName = "Kasia",
                            LastName = "Farba",
                            MaxWeight = 45
                        },
                        new
                        {
                            IdCharacter = 6,
                            CurrentWeight = 12,
                            FirstName = "Krzysztof",
                            LastName = "Krawczyk",
                            MaxWeight = 31000
                        });
                });

            modelBuilder.Entity("kolos2.Models.Character_title", b =>
                {
                    b.Property<int>("IdCharacter")
                        .HasColumnType("int");

                    b.Property<int>("IdTitle")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCharacter", "IdTitle");

                    b.HasIndex("IdTitle");

                    b.ToTable("character_titles");

                    b.HasData(
                        new
                        {
                            IdCharacter = 1,
                            IdTitle = 1,
                            AcquiredAt = new DateTime(2024, 6, 14, 14, 30, 1, 827, DateTimeKind.Local).AddTicks(1442)
                        },
                        new
                        {
                            IdCharacter = 2,
                            IdTitle = 2,
                            AcquiredAt = new DateTime(2024, 6, 14, 14, 30, 1, 829, DateTimeKind.Local).AddTicks(7098)
                        },
                        new
                        {
                            IdCharacter = 3,
                            IdTitle = 3,
                            AcquiredAt = new DateTime(2024, 6, 14, 14, 30, 1, 829, DateTimeKind.Local).AddTicks(7128)
                        });
                });

            modelBuilder.Entity("kolos2.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("IdItem");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Name = "Glove",
                            Weight = 5
                        },
                        new
                        {
                            IdItem = 2,
                            Name = "Sword",
                            Weight = 10
                        },
                        new
                        {
                            IdItem = 3,
                            Name = "Goblin",
                            Weight = 15
                        },
                        new
                        {
                            IdItem = 4,
                            Name = "Hat",
                            Weight = 1
                        },
                        new
                        {
                            IdItem = 5,
                            Name = "Mushroom",
                            Weight = 5
                        },
                        new
                        {
                            IdItem = 6,
                            Name = "Pepper",
                            Weight = 12
                        },
                        new
                        {
                            IdItem = 7,
                            Name = "Potion",
                            Weight = 3
                        },
                        new
                        {
                            IdItem = 8,
                            Name = "Cat",
                            Weight = 13
                        });
                });

            modelBuilder.Entity("kolos2.Models.Title", b =>
                {
                    b.Property<int>("IdTitle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTitle"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTitle");

                    b.ToTable("titles");

                    b.HasData(
                        new
                        {
                            IdTitle = 1,
                            Name = "Archer"
                        },
                        new
                        {
                            IdTitle = 2,
                            Name = "Wizard"
                        },
                        new
                        {
                            IdTitle = 3,
                            Name = "Ruler"
                        },
                        new
                        {
                            IdTitle = 4,
                            Name = "Magician"
                        },
                        new
                        {
                            IdTitle = 5,
                            Name = "Princess"
                        },
                        new
                        {
                            IdTitle = 6,
                            Name = "Fighter"
                        });
                });

            modelBuilder.Entity("kolos2.Models.Backpack", b =>
                {
                    b.HasOne("kolos2.Models.Character", "Character")
                        .WithMany("Backpacks")
                        .HasForeignKey("IdCharacter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolos2.Models.Item", "Item")
                        .WithMany("Backpacks")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("kolos2.Models.Character_title", b =>
                {
                    b.HasOne("kolos2.Models.Character", "Character")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("IdCharacter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolos2.Models.Title", "Title")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("IdTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("kolos2.Models.Character", b =>
                {
                    b.Navigation("Backpacks");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("kolos2.Models.Item", b =>
                {
                    b.Navigation("Backpacks");
                });

            modelBuilder.Entity("kolos2.Models.Title", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
